### ISSUE TITLE
Uppercase validation.

### ISSUE THREAD

**Issue by ghost** [rineddy/purebasic-extension#1]
All uppercase words get a green line and a warning in Problems window with the following text ""word" is all uppercase." and the source is "ex". Since uppercase words aren't a problem i Purebasic, In fact used in constants. I suggest you  either remove check or make it optional.

The message originates from file: /server/PureBasicValidation.ts, line: 33-34
One quick way to get rid of it is to remove line 81 ( pb.validation.validate(changed.document); ) in  /server/index.ts or update the function "validate" in /server/PureBasicValidation.ts

**Comment by rineddy** [comment]
I'll fix this one.
